# =============================================
#  PERFIL PADRAO: POSTGRESQL (SUPABASE)
# =============================================

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?user=postgres.vuqpszdodiqbhgaojtrh&password=falucpkVVZI8ik4i&prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Impede que o Spring rode data.sql ou schema.sql automaticamente
# Isso garante que a inserção ocorra apenas quando você rodar o script manualmente
spring.sql.init.mode=never

server.address=0.0.0.0
server.port=8080